name: Example Workflow

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run a script
      run: echo "This is a script step"
      
    - name: Install Dependencies
      run: npm install

    - name: Run Tests
      run: npm test
